credentials:
  usernames:
    nikolas.g:
      email: nikolas.s@transpotech.com.br
      failed_login_attempts: 0
      logged_in: False
      name: Nikolas Geremias
      password: geremias123
    douglas.d:
      email: douglas.debatim@transpotech.com.br
      failed_login_attempts: 0
      logged_in: False
      name: Douglas Debatim
      password: debatim123
    vinicius.b:
      email: vinicius.b@transpotech.com.br
      failed_login_attempts: 0
      logged_in: False
      name: Vinicius Bachtold
      password: bachtold123
    jackson.l:
      email: jackson.l@transpotech.com.br
      failed_login_attempts: 0
      logged_in: False
      name: Jackson Laurenço
      password: laurenco123
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com